---
- name: Clone specific Netbird version
  hosts: default
  become: false
  vars:
    netbird_repo: "https://github.com/netbirdio/netbird/"
    netbird_version: "v0.43.2"  # ← Set your desired version here
    clone_dest: "/home/ubuntu/netbird"  # Set your destination path

  tasks:
    - name: Verify git is installed
      ansible.builtin.package:
        name: git
        state: present
      become: true

    - name: Clone the specified release
      ansible.builtin.git:
        repo: "{{ netbird_repo }}"
        dest: "{{ clone_dest }}"
        version: "{{ netbird_version }}"
        depth: 1
        force: yes
      register: clone_result

    - name: Verify clone was successful
      ansible.builtin.debug:
        msg: "Successfully cloned Netbird {{ netbird_version }} to {{ clone_dest }}"
      when: clone_result.changed

    - name: Show clone status if already exists
      ansible.builtin.debug:
        msg: "Netbird {{ netbird_version }} already exists at {{ clone_dest }}"
      when: not clone_result.changed